//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Raihan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auther
    {
        public int AutherID { get; set; }
        public string AutherName { get; set; }
        public string AutherAddress { get; set; }
        public int ContactNo { get; set; }
    }
}
