//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Raihan.Models
{
    using MvcProject_Raihan.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookDetail
    {
        public int BookDetailsID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> PublisherId { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/mm/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Purchase Date")]
        [DataType(DataType.Date)]
        [CustomHireDate(ErrorMessage = "Hire Date must be less than or equal to Today's Date")]
        public System.DateTime PurchaseDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/mm/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Return Date")]
        [DataType(DataType.Date)]
        [CustomHireDate(ErrorMessage = "Hire Date must be less than or equal to Today's Date")]
        public System.DateTime ReturnDate { get; set; }
        public int BookPrice { get; set; }
        public int ServiceCharge { get; set; }
        public int DeleveryCharge { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Publisher Publisher { get; set; }
    }
}
