//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Raihan.Models
{
    using MvcProject_Raihan.CustomAttribute;
    using MvcProject_Raihan.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CustomerID { get; set; }
        [Required(ErrorMessage = "You Can't Leave it Blank")]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Enter Minimum 2 or maximum 40 chacacter !!")]
        [Display(Name = "Customer Name", Description = "Name of the Customer")]
        public string Name { get; set; }
        [Range(6, 60, ErrorMessage = "Age Must be between 6 to 60")]
        public int Age { get; set; }
        [Required(ErrorMessage = "You Can't Leave it Blank")]
       
        [DisplayFormat(DataFormatString = "{0:dd/mm/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        [CustomHireDate(ErrorMessage = "Hire Date must be less than or equal to Today's Date")]
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        [MyAttribute]
        public string Phone { get; set; }
        [Required(ErrorMessage = "You Can't Leave it Blank")]
        public string Email { get; set; }
    }
}
