//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Raihan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        [Required(ErrorMessage ="This filed must be full")]
        public string Name { get; set; }
        public string Designation { get; set; }
        [Required(ErrorMessage = "This filed must be full")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "This filed must be full")]
        public string Email { get; set; }
        [Display(Name ="Picture")]
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }
        public Employee()
        {
            ImagePath = "~/ AppFiles / Images ";
        }
    }
}
