//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Raihan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentID { get; set; }
        [Required(ErrorMessage ="This filed must be fillup!!!")]
        public string StudentName { get; set; }
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "This filed must be fillup!!!")]
        public string CellPhone { get; set; }
        [Required(ErrorMessage = "This filed must be fillup!!!")]
        public string ContactAddress { get; set; }
    }
}
